# CMake generated Testfile for 
# Source directory: /Users/Rebeka/Downloads/kyber-main/ref
# Build directory: /Users/Rebeka/Downloads/kyber-main/ref/ref
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(kyber512_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kyber512_ref")
set_tests_properties(kyber512_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;87;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kex512_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kex512_ref")
set_tests_properties(kex512_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;88;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kyber512-90s_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kyber512-90s_ref")
set_tests_properties(kyber512-90s_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;89;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kex512-90_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kex512-90s_ref")
set_tests_properties(kex512-90_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;90;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kyber768_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kyber768_ref")
set_tests_properties(kyber768_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;91;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kex768_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kex768_ref")
set_tests_properties(kex768_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;92;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kyber768-90s_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kyber768-90s_ref")
set_tests_properties(kyber768-90s_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;93;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kex768-90_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kex768-90s_ref")
set_tests_properties(kex768-90_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;94;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kyber1024_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kyber1024_ref")
set_tests_properties(kyber1024_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;95;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kex1024_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kex1024_ref")
set_tests_properties(kex1024_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;96;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kyber1024-90s_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kyber1024-90s_ref")
set_tests_properties(kyber1024-90s_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;97;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(kex1024-90_ref "/Users/Rebeka/Downloads/kyber-main/ref/ref/test_kex1024-90s_ref")
set_tests_properties(kex1024-90_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;98;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(vectors512_ref "sh" "-c" "\"/Users/Rebeka/Downloads/kyber-main/ref/ref/test_vectors512_ref\" > tvecs512")
set_tests_properties(vectors512_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;109;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(vectors512-90s_ref "sh" "-c" "\"/Users/Rebeka/Downloads/kyber-main/ref/ref/test_vectors512-90s_ref\" > tvecs512-90s")
set_tests_properties(vectors512-90s_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;110;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(vectors768_ref "sh" "-c" "\"/Users/Rebeka/Downloads/kyber-main/ref/ref/test_vectors768_ref\" > tvecs768")
set_tests_properties(vectors768_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;111;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(vectors768-90s_ref "sh" "-c" "\"/Users/Rebeka/Downloads/kyber-main/ref/ref/test_vectors768-90s_ref\" > tvecs768-90s")
set_tests_properties(vectors768-90s_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;112;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(vectors1024_ref "sh" "-c" "\"/Users/Rebeka/Downloads/kyber-main/ref/ref/test_vectors1024_ref\" > tvecs1024")
set_tests_properties(vectors1024_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;113;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(vectors1024-90s_ref "sh" "-c" "\"/Users/Rebeka/Downloads/kyber-main/ref/ref/test_vectors1024-90s_ref\" > tvecs1024-90s")
set_tests_properties(vectors1024-90s_ref PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;114;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
add_test(hashes "sha256sum" "-c" "../../SHA256SUMS")
set_tests_properties(hashes PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;117;add_test;/Users/Rebeka/Downloads/kyber-main/ref/CMakeLists.txt;0;")
