# CMake generated Testfile for 
# Source directory: /Users/Rebeka/Downloads/SIKE/test
# Build directory: /Users/Rebeka/Downloads/SIKE/SIKEp434/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SIKEp434-arithmetic "sike_test" "SIKEp434" "arith")
set_tests_properties(SIKEp434-arithmetic PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;5;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp434-sidh "sike_test" "SIKEp434" "sidh_int")
set_tests_properties(SIKEp434-sidh PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;6;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp434-pke "sike_test" "SIKEp434" "pke")
set_tests_properties(SIKEp434-pke PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;7;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp434-sike "sike_test" "SIKEp434" "sike")
set_tests_properties(SIKEp434-sike PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;8;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp434-sike-int "sike_test" "SIKEp434" "sike_int")
set_tests_properties(SIKEp434-sike-int PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;9;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp503-arithmetic "sike_test" "SIKEp503" "arith")
set_tests_properties(SIKEp503-arithmetic PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;11;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp503-sidh "sike_test" "SIKEp503" "sidh_int")
set_tests_properties(SIKEp503-sidh PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;12;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp503-pke "sike_test" "SIKEp503" "pke")
set_tests_properties(SIKEp503-pke PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;13;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp503-sike "sike_test" "SIKEp503" "sike")
set_tests_properties(SIKEp503-sike PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;14;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp503-sike-int "sike_test" "SIKEp503" "sike_int")
set_tests_properties(SIKEp503-sike-int PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;15;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp610-arithmetic "sike_test" "SIKEp610" "arith")
set_tests_properties(SIKEp610-arithmetic PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;17;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp610-sidh "sike_test" "SIKEp610" "sidh_int")
set_tests_properties(SIKEp610-sidh PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;18;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp610-pke "sike_test" "SIKEp610" "pke")
set_tests_properties(SIKEp610-pke PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;19;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp610-sike "sike_test" "SIKEp610" "sike")
set_tests_properties(SIKEp610-sike PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;20;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp610-sike-int "sike_test" "SIKEp610" "sike_int")
set_tests_properties(SIKEp610-sike-int PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;21;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp751-arithmetic "sike_test" "SIKEp751" "arith")
set_tests_properties(SIKEp751-arithmetic PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;23;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp751-sidh "sike_test" "SIKEp751" "sidh_int")
set_tests_properties(SIKEp751-sidh PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;24;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp751-pke "sike_test" "SIKEp751" "pke")
set_tests_properties(SIKEp751-pke PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;25;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp751-sike "sike_test" "SIKEp751" "sike")
set_tests_properties(SIKEp751-sike PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;26;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
add_test(SIKEp751-sike-int "sike_test" "SIKEp751" "sike_int")
set_tests_properties(SIKEp751-sike-int PROPERTIES  _BACKTRACE_TRIPLES "/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;27;add_test;/Users/Rebeka/Downloads/SIKE/test/CMakeLists.txt;0;")
